### ISSUE TITLE
Could not find firebase-common-debug.aar in version 1.3.0

### ISSUE THREAD

**Issue by tiagonuneslx** [GitLiveApp/firebase-kotlin-sdk#185]
```
val commonMain by getting {
    dependencies {
        implementation("dev.gitlive:firebase-firestore:1.3.0")
    }
}
```

Using 1.3.0 instead of 1.2.0 results in this build error:

> Could not resolve all files for configuration ':androidApp:debugRuntimeClasspath'.
   > Failed to transform firebase-common-debug.aar (dev.gitlive:firebase-common-android-debug:1.3.0) to match attributes {artifactType=android-databinding, com.android.build.api.attributes.BuildTypeAttr=debug, com.android.build.api.attributes.VariantAttr=debug, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not find firebase-common-debug.aar (dev.gitlive:firebase-common-android-debug:1.3.0).
        Searched in the following locations:
            https://repo.maven.apache.org/maven2/dev/gitlive/firebase-common-android-debug/1.3.0/firebase-common-android-debug-1.3.0.aar

**Comment by jfreeley** [comment]
Can confirm I'm getting the same 👍

**Comment by jfreeley** [comment]
It looks like all except the .aar file is in that directory
1.3.0: https://repo.maven.apache.org/maven2/dev/gitlive/firebase-common-android-debug/1.3.0/
1.2.0: https://repo.maven.apache.org/maven2/dev/gitlive/firebase-common-android-debug/1.2.0/

**Comment by afTrolle** [comment]
I'm getting the same issue for firebase-auth:1.3.0
```
 val commonMain by getting {
    dependencies {
       implementation("dev.gitlive:firebase-auth:1.3.0")
    }
}
 ```
 Gradle Sync Error
 ```
 org.gradle.internal.resolve.ArtifactNotFoundException: Could not find firebase-common-debug.aar (dev.gitlive:firebase-common-android-debug:1.3.0).
Searched in the following locations:
    https://repo.maven.apache.org/maven2/dev/gitlive/firebase-common-android-debug/1.3.0/firebase-common-android-debug-1.3.0.aar
	at org.gradle.internal.resolve.result.DefaultBuildableArtifactResolveResult.notFound(DefaultBuildableArtifactResolveResult.java:28)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$LocateInCacheRepositoryAccess.resolveArtifactFromCache(CachingModuleComponentRepository.java:345)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$LocateInCacheRepositoryAccess.resolveArtifact(CachingModuleComponentRepository.java:297)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.lambda$resolveArtifact$15(ErrorHandlingModuleComponentRepository.java:181)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.tryResolveAndMaybeBlacklist(ErrorHandlingModuleComponentRepository.java:237)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.performOperationWithRetries(ErrorHandlingModuleComponentRepository.java:203)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.resolveArtifact(ErrorHandlingModuleComponentRepository.java:179)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainArtifactResolver.resolveArtifact(RepositoryChainArtifactResolver.java:100)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.DefaultArtifactSet$LazyArtifactSupplier.calculateValue(DefaultArtifactSet.java:273)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.DefaultArtifactSet$LazyArtifactSupplier.calculateValue(DefaultArtifactSet.java:244)
	at org.gradle.internal.model.CalculatedValueContainer$CalculationState.lambda$attachValue$0(CalculatedValueContainer.java:216)
	at org.gradle.internal.Try.ofFailable(Try.java:39)
	at org.gradle.internal.model.CalculatedValueContainer$CalculationState.attachValue(CalculatedValueContainer.java:211)
	at org.gradle.internal.model.CalculatedValueContainer.finalizeIfNotAlready(CalculatedValueContainer.java:184)
	at org.gradle.internal.model.CalculatedValueContainer.finalizeIfNotAlready(CalculatedValueContainer.java:175)
	at org.gradle.api.internal.artifacts.PreResolvedResolvableArtifact.getFile(PreResolvedResolvableArtifact.java:88)
	at org.jetbrains.plugins.gradle.tooling.util.resolve.DependencyResolverImpl.resolveDependencies(DependencyResolverImpl.java:239)
	at org.jetbrains.plugins.gradle.tooling.util.resolve.DependencyResolverImpl.resolveDependencies(DependencyResolverImpl.java:119)
	at org.jetbrains.kotlin.gradle.KotlinMPPGradleModelBuilder.buildDependencies(KotlinMPPGradleModelBuilder.kt:224)
```

**Comment by Reedyuk** [comment]
Hi guys, sorry about that, was a problem with the publishing. Its now fixed in 1.3.1, please try it.
Closing as i was able to reproduce and fixed with 1.3.1

**Comment by afTrolle** [comment]
Thank you @Reedyuk, 1.3.1 works!
