### ISSUE TITLE
Build fails for iOS

### ISSUE THREAD

**Issue by litclimbing** [GitLiveApp/firebase-kotlin-sdk#255]
I'm trying to start working on the library to add TImestamp support but I can't get it to compile for iOS.

I get the following error for all the iOS tasks
`> Task :firebase-app:cinteropFirebaseCoreIosX64
Exception in thread "main" java.lang.Error: /var/folders/66/rtn2jsd10k70lynsc36pmx1w0000gn/T/11612131558186524609.m:1:9: fatal error: could not build module 'FirebaseCore'
	at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:192)
	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesASTFiles(ModuleSupport.kt:68)
	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesInfo(ModuleSupport.kt:14)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.buildNativeLibrary(main.kt:531)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:268)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:76)
	at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:45)
	at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:38)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:60)`

I did a fresh clone of the repo, opened it in Android Studio, and ran the publishToMavenLocal task. Am I missing something?

**Comment by litclimbing** [comment]
I figured out this is due to an incompatibility with XCode 13. Originally I tried to downgrade to XCode 12.5.1 but this won't run on Monterey. I came across the original report here https://youtrack.jetbrains.com/issue/KT-48807 and created a PR  (#256) for the workaround.

**Comment by nbransby** [comment]
This should be fixed in 15.0
