### ISSUE TITLE
PERMISSION_DENIED crashes the app

### ISSUE THREAD

**Issue by valeriyo** [GitLiveApp/firebase-kotlin-sdk#350]
I'm doing `firestore.collection(COLLECTION_PATH).document(docId).snapshots` and if that document isn't allowed to be accessed by the Firestore rules, the app crashes with:

```
FATAL EXCEPTION: main
 com.google.firebase.firestore.FirebaseFirestoreException: PERMISSION_DENIED: Missing or insufficient permissions.
    at com.google.firebase.firestore.util.Util.exceptionFromStatus(Util.java:112)
    at com.google.firebase.firestore.core.EventManager.onError(EventManager.java:166)
    at com.google.firebase.firestore.core.SyncEngine.removeAndCleanupTarget(SyncEngine.java:600)
    at com.google.firebase.firestore.core.SyncEngine.handleRejectedListen(SyncEngine.java:436)
    at com.google.firebase.firestore.core.MemoryComponentProvider$RemoteStoreCallback.handleRejectedListen(MemoryComponentProvider.java:104)
    at com.google.firebase.firestore.remote.RemoteStore.processTargetError(RemoteStore.java:581)
    at com.google.firebase.firestore.remote.RemoteStore.handleWatchChange(RemoteStore.java:465)
    at com.google.firebase.firestore.remote.RemoteStore.access$100(RemoteStore.java:57)
    at com.google.firebase.firestore.remote.RemoteStore$1.onWatchChange(RemoteStore.java:180)
    at com.google.firebase.firestore.remote.WatchStream.onNext(WatchStream.java:109)
    at com.google.firebase.firestore.remote.WatchStream.onNext(WatchStream.java:38)
    at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.lambda$onNext$1$com-google-firebase-firestore-remote-AbstractStream$StreamObserver(AbstractStream.java:119)
    at com.google.firebase.firestore.remote.AbstractStream$StreamObserver$$ExternalSyntheticLambda2.run(Unknown Source:4)
    at com.google.firebase.firestore.remote.AbstractStream$CloseGuardedRunner.run(AbstractStream.java:67)
    at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.onNext(AbstractStream.java:110)
    at com.google.firebase.firestore.remote.FirestoreChannel$1.onMessage(FirestoreChannel.java:140)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:662)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:647)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:234)
    at java.lang.Thread.run(Thread.java:1012)
    Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@eba5e37, Dispatchers.Main.immediate]
 Caused by: io.grpc.StatusException: PERMISSION_DENIED: Missing or insufficient permissions.
    at io.grpc.Status.asException(Status.java:547)
    at com.google.firebase.firestore.util.Util.exceptionFromStatus(Util.java:110)
    ... 26 more
```

Why is this crashing the app instead of bubbling up the FirebaseFirestoreException to me?

**Comment by valeriyo** [comment]
Well, that's because `snapshots` in case of exception, closes the flow, and that exception is thrown into the coroutine context, which was `viewModelScope` - and without an exception handler, it's fatal.

I think `snapshots` is just badly designed. Instead of returning `Flow<DocumentSnapshot>` we would be better off with `Flow<Result<DocumentSnapshot>>` - so that the `FirebaseFirestoreException` could propagate within the flow itself, and pose no risk of being fatal for the app. Same goes for the `Query.snapshots` flow.

**Comment by Reedyuk** [comment]
@valeriyo Don't forget that this library is just a wrapper of the native libraries and so if the native library(android firebase sdk) was to behave this way, then you would have the same issue.
The solution would be to suggest such a change in the native android sdk so that the wrapper would inherit this.

**Comment by tellypresence** [comment]
Ran into the same issue.  This was after porting from native firestore to "gitlive" wrapper, so was a surprise as I'd never seen the error before and wasn't aware I'd done anything to change the internal operation (the main change when porting was swapping from hashmaps to data classes)

For me this happens on a fresh install of android app (app crashes on launch) with the `PERMISSION_DENIED` crash; on relaunch the app starts up OK...

<details>
<summary>Expand to view stack trace</summary>
<tt>
com.google.firebase.firestore.FirebaseFirestoreException: PERMISSION_DENIED: Missing or insufficient permissions.
                                                                                                    	at com.google.firebase.firestore.util.Util.exceptionFromStatus(Util.java:155)
                                                                                                    	at com.google.firebase.firestore.core.EventManager.onError(EventManager.java:247)
                                                                                                    	at com.google.firebase.firestore.core.SyncEngine.removeAndCleanupTarget(SyncEngine.java:642)
                                                                                                    	at com.google.firebase.firestore.core.SyncEngine.handleRejectedListen(SyncEngine.java:478)
                                                                                                    	at com.google.firebase.firestore.core.MemoryComponentProvider$RemoteStoreCallback.handleRejectedListen(MemoryComponentProvider.java:125)
                                                                                                    	at com.google.firebase.firestore.remote.RemoteStore.processTargetError(RemoteStore.java:596)
                                                                                                    	at com.google.firebase.firestore.remote.RemoteStore.handleWatchChange(RemoteStore.java:479)
                                                                                                    	at com.google.firebase.firestore.remote.RemoteStore.access$100(RemoteStore.java:60)
                                                                                                    	at com.google.firebase.firestore.remote.RemoteStore$1.onWatchChange(RemoteStore.java:188)
                                                                                                    	at com.google.firebase.firestore.remote.WatchStream.onNext(WatchStream.java:114)
                                                                                                    	at com.google.firebase.firestore.remote.WatchStream.onNext(WatchStream.java:38)
                                                                                                    	at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.lambda$onNext$1$com-google-firebase-firestore-remote-AbstractStream$StreamObserver(AbstractStream.java:126)
                                                                                                    	at com.google.firebase.firestore.remote.AbstractStream$StreamObserver$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at com.google.firebase.firestore.remote.AbstractStream$CloseGuardedRunner.run(AbstractStream.java:67)
                                                                                                    	at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.onNext(AbstractStream.java:113)
                                                                                                    	at com.google.firebase.firestore.remote.FirestoreChannel$1.onMessage(FirestoreChannel.java:162)
                                                                                                    	at io.grpc.internal.DelayedClientCall$DelayedListener.onMessage(DelayedClientCall.java:473)
                                                                                                    	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:667)
                                                                                                    	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:654)
                                                                                                    	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
                                                                                                    	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:524)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:317)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:348)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
                                                                                                    	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
                                                                                                    	at java.lang.Thread.run(Thread.java:1119)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@cf90630, Dispatchers.IO]                               
</tt>
</details>
