### ISSUE TITLE
JVM crash on init

### ISSUE THREAD

**Issue by dmazgalin** [GitLiveApp/firebase-kotlin-sdk#565]
Hi Folks, I was trying to make a multiplatform app. At the moment have some issues with Firebase init.

Have following code: 

        val options = FirebaseOptions(
            applicationId = "***",
            projectId = "***",
            apiKey = "***"
        )

        Firebase.initialize(Application(), options, "Sample")

after this line the app is showing in console following stack trace.

FirebaseApp Device unlocked: initializing all Firebase APIs for app Sample
kotlinx.serialization.json.internal.JsonDecodingException: Cannot read Json element because of unexpected end of the input at path: $
JSON input: 
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:598)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:596)
	at kotlinx.serialization.json.internal.JsonTreeReader.read(JsonTreeReader.kt:107)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeJsonElement(StreamingJsonDecoder.kt:50)
	at kotlinx.serialization.json.JsonElementSerializer.deserialize(JsonElementSerializers.kt:50)
	at kotlinx.serialization.json.JsonElementSerializer.deserialize(JsonElementSerializers.kt:27)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
	at kotlinx.serialization.json.Json.parseToJsonElement(Json.kt:136)
	at com.google.firebase.auth.FirebaseAuth.<init>(FirebaseAuth.kt:153)
	at com.google.firebase.auth.FirebaseAuthRegistrar.lambda$getComponents$0(FirebaseAuthRegistrar.java:21)
	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:160)
	at com.google.firebase.components.Lazy.get(Lazy.java:53)
	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:322)
	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:312)
	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:607)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:300)
	at dev.gitlive.firebase.FirebaseKt.initialize(firebase.kt:27)
	at com.sample.ComposableSingletons$ApplicationKt$lambda-3$1.invoke(Application.kt:67)

**Comment by nbransby** [comment]
See https://github.com/GitLiveApp/firebase-kotlin-sdk?tab=readme-ov-file#multiplatform

**Comment by dmazgalin** [comment]
@nbransby 
Additional initialization was done with following code

fun initFirebaseJVM(storage: LocalPreferencesRepository) {
FirebasePlatform.initializeFirebasePlatform(object : FirebasePlatform() {
        override fun store(key: String, value: String) = storage.setString(key, value)
        override fun retrieve(key: String) = storage.getString(key)
        override fun clear(key: String) {
            storage.setString(key, "")
        }

        override fun log(msg: String) = println(msg)
    })
}

I was following full guidance for implementing it. Still doesn#t work

**Comment by nbransby** [comment]
If you analyse the stack trace it would appear the your `override fun retrieve(key: String) = storage.getString(key)` is not returning the expected value

![image](https://github.com/user-attachments/assets/3d51a93d-2075-49e7-a37c-05a942c7ec44)

**Comment by dmazgalin** [comment]
@nbransby Yes you are right. The problem was when I wrote custom implementation for storing the preferences. 

Retrive method should return null. Otherwise it is crashing with the stacktrace above.

Proper implementation gives no error.
        override fun retrieve(key: String): String? {
            println("Get key $key, value ${storage.getStringOrNull(key)}")
            return storage.getStringOrNull(key)
        }
