### ISSUE TITLE
App crashing in Desktop with Module with the Main dispatcher is missing.

### ISSUE THREAD

**Issue by dinesh-thiyagarajan** [GitLiveApp/firebase-kotlin-sdk#566]
Getting this below error even after matching the coroutines versions. Was getting this error only after adding gitLive SDK to the project while using auth and firebase - database modules. but the same code is working fine while running this in android app

<img width="794" alt="Screenshot 2024-07-15 at 9 24 51 PM" src="https://github.com/user-attachments/assets/a2dc9889-27bd-4d8d-9456-7a517ee2b162">

`Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core'
	at kotlinx.coroutines.internal.MainDispatchersKt.throwMissingMainDispatcherException(MainDispatchers.kt:77)
	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:108)
	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:92)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:315)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:21)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:88)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at auth.viewModels.AuthViewModel.<init>(AuthViewModel.kt:21)
	at ComposableSingletons$MainKt$lambda-1$1.invoke(main.kt:44)
	at ComposableSingletons$MainKt$lambda-1$1.invoke(main.kt:18)`

**Comment by dinesh-thiyagarajan** [comment]
https://github.com/GitLiveApp/firebase-java-sdk/issues/6 

Updating coroutines version to org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.9.0-RC .  seems to have fixed the issue on Mac
