### ISSUE TITLE
NotImplementedError in EmailAuthProvider.getCredential

### ISSUE THREAD

**Issue by valeriyo** [GitLiveApp/firebase-kotlin-sdk#582]
I'm getting on JVM/Desktop:

```
Exception in thread "AWT-EventQueue-0" kotlin.NotImplementedError: An operation is not implemented.
        at com.google.firebase.auth.EmailAuthProvider.getCredential(EmailAuthProvider.java:7)
        at dev.gitlive.firebase.auth.EmailAuthProvider.credential(credentials.kt:30)
```

having in `build.gradle.kts`:

```
    commonMain.dependencies {
      implementation(libs.gitlive.firebase.auth)
      ...
```

and in `libs.versions.toml`:
```
[versions]
gitlive = "1.13.0"

[libraries]
gitlive-firebase-auth = { module = "dev.gitlive:firebase-auth", version.ref = "gitlive" }
```

Any clue? Thanks

**Comment by valeriyo** [comment]
Aah... I have to use `signInWithEmailAndPassword`, because only very few methods are implemented:

https://github.com/GitLiveApp/firebase-java-sdk?tab=readme-ov-file#limitations
