### ISSUE TITLE
set/add functions don't return when no internet connection - Firestore

### ISSUE THREAD

**Issue by stevdza-san** [GitLiveApp/firebase-kotlin-sdk#631]
Here's an example of one of my functions, for updating a vehicle object in Firebase. When there is an internet connection, the function properly returns a RequestState object.

```kotlin
override suspend fun updateVehicle(vehicle: FirebaseVehicle): RequestState<Unit> {
        return try {
            val userId = getCurrentUserId()
            val specialCharsNotAllowed = getString(Res.string.special_chars_not_allowed)
            val userNotFound = getString(Res.string.user_not_found)

            if (userId != null) {
                if (!containsSpecialCharacters(vehicle.plateNumber)) {
                        val database = Firebase.firestore
                        database.collection(collectionPath = "vehicles")
                            .document(documentPath = vehicle._id)
                            .set(vehicle.copy(ownerId = userId))
                        RequestState.Success(Unit)
                } else {
                    RequestState.Error(message = specialCharsNotAllowed)
                }
            } else {
                RequestState.Error(message = userNotFound)
            }
        } catch (e: Exception) {
            RequestState.Error(message = e.message.toString())
        }
    }
```
    
    
However, when I trigger this same function when there is no an internet connection, then this function never returns the above-mentioned RequestState (Even though the operation was successful). It just prints in the log, and my function doesn't catch any exception actually. Am I doing something wrong?
    
```
Stream closed with status: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
                                                                	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
                                                                	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
                                                                	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
                                                                	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                	at java.lang.Thread.run(Thread.java:1012)
                                                                Caused by: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
                                                                	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
                                                                	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
                                                                	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
                                                                	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:632)
                                                                	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
                                                                	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282) 
                                                                	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318) 
                                                                	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
                                                                	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
                                                                	at java.lang.Thread.run(Thread.java:1012) 
                                                                }.```

**Comment by nbransby** [comment]
The function will return when the write finishes - as you have offline persistence enabled it will write to the local database but won't finish until you go back online, this is the standard firestore behaviour of the native sdks

**Comment by stevdza-san** [comment]
Hmm, so what's the best solution here? I don't think adding withTimeout {} seems like a good approach, but I don't see any other?

**Comment by nbransby** [comment]
Either disable offline persistence and it will fail and throw on no network or keep it enabled and consider the value set and trust it will sync to the server once the client is back online
