### ISSUE TITLE
Android Crashlytics Stacktrace missing

### ISSUE THREAD

**Issue by henkehagstrom** [GitLiveApp/firebase-kotlin-sdk#663]
Hey

Love this SDK, but I am having trouble with tracing crashes back to its origin in my code.

```
Fatal Exception: a4.h: There is no user record corresponding to this identifier. The user may have been deleted.
       at com.google.firebase.auth.FirebaseAuthInvalidUserException.<init>(FirebaseAuthInvalidUserException.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzadg.zza(com.google.firebase:firebase-auth@@23.1.0:6)
       at com.google.android.gms.internal.firebase-auth-api.zzaef.zza(com.google.firebase:firebase-auth@@23.1.0:21)
       at com.google.android.gms.internal.firebase-auth-api.zzady.zza(com.google.firebase:firebase-auth@@23.1.0:32)
       at com.google.android.gms.internal.firebase-auth-api.zzaea.zza(com.google.firebase:firebase-auth@@23.1.0:71)
       at com.google.android.gms.internal.firebase-auth-api.zzade.zza(com.google.firebase:firebase-auth@@23.1.0:46)
       at com.google.android.gms.internal.firebase-auth-api.zzzu.zza(com.google.firebase:firebase-auth@@23.1.0:3)
       at com.google.android.gms.internal.firebase-auth-api.zzaeo.zza(com.google.firebase:firebase-auth@@23.1.0:15)
       at com.google.android.gms.internal.firebase-auth-api.zzaeo.zza(com.google.firebase:firebase-auth@@23.1.0:64)
       at com.google.android.gms.internal.firebase-auth-api.zzadv.zza(com.google.firebase:firebase-auth@@23.1.0:62)
       at com.google.android.gms.internal.firebase-auth-api.zzzk.zzb(com.google.firebase:firebase-auth@@23.1.0:162)
       at com.google.android.gms.internal.firebase-auth-api.zzadh.zzb(com.google.firebase:firebase-auth@@23.1.0:130)
       at com.google.android.gms.internal.firebase-auth-api.zzaci.zza(com.google.firebase:firebase-auth@@23.1.0:17)
       at com.google.android.gms.internal.firebase-auth-api.zzaeh.run(com.google.firebase:firebase-auth@@23.1.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:764)
```
       
I can of course guess, but it would be nice with some definitive cause for this. Am I missing some setting or is this expected behaviour? FYI, this crash sometimes appears when using this:
       
       val result = Firebase.auth.signInWithEmailAndPassword(emailText, passwordText)

**Comment by nbransby** [comment]
You would get the same stack trace using the android ask directly, it's because the Auth module is not open source and is obfuscated. You'll need to just go off the error message which is fortunately pretty clear as to the issue.

**Comment by nbransby** [comment]
No, you would get the exact same stack trace if you were using the native firebase android SDK, that stacktrace is entirely inside the native SDK. If you are wondering why you can't see a reference to your own code in there it's because it originated from a background thread started by the SDK, not your code.

**Comment by henkehagstrom** [comment]
Alright, got it! Closing this issue :)
