### ISSUE TITLE
KMM error: java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'

### ISSUE THREAD

**Issue by CiprianGabor** [GitLiveApp/firebase-kotlin-sdk#672]
Any idea how to solve this error using Firebase Auth: auth.createUserWithEmailAndPassword(user.email, password)

```
Failed to get service from broker. 
java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'.
at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
at android.os.Parcel.createException(Parcel.java:3053)
at android.os.Parcel.readException(Parcel.java:3036)
at android.os.Parcel.readException(Parcel.java:2978)
at angb.a(:com.google.android.gms@244337029@24.43.37 (190400-693941914):36)
at anei.z(:com.google.android.gms@244337029@24.43.37 (190400-693941914):143)
at amln.run(:com.google.android.gms@244337029@24.43.37 (190400-693941914):54)
```

The versions that I use for my KMM app:

```
dependencies {
        classpath("com.google.gms:google-services:4.4.2")
    }

implementation("dev.gitlive:firebase-firestore:1.10.4")
implementation("dev.gitlive:firebase-common:1.10.4")
implementation("dev.gitlive:firebase-auth:1.10.4")
```

The user is created but my app crashes because of the error.

Have a great day!

**Comment by anggrayudi** [comment]
This isn't coming from this SDK, and it almost certainly isn't what's crashing your app.

Every frame in that trace is either `android.os.Parcel` or obfuscated Play Services internals — `angb.a`, `anei.z`, `amln.run`, all tagged `:com.google.android.gms@244337029@24.43.37`. There's no app frame, no `dev.gitlive` frame and no `com.google.firebase` frame in it, and `amln.run` is a `Runnable` on a Play Services background thread. So that `SecurityException` is constructed and handled entirely inside Play Services; it never propagates out to the SDK or to your code. It's also not a crash trace — there's no `FATAL EXCEPTION` header and no `Caused by` chain into your app.

That matches the rest of the evidence:

- You say the user *is* created, so the call itself succeeded.
- `createUserWithEmailAndPassword` here is a one line forward to the Android SDK's `Task` plus `await()`, with nothing in between that could turn a background log into a throw.
- The same message is reported verbatim against completely unrelated Firebase wrappers — flutterfire firebase/flutterfire#13440 and firebase/flutterfire#13560, both closed by Firebase as `resolution: invalid`, and the AdMob SDK — which places it at the Play Services layer, below any wrapper.
- @Sumanthboya hitting it on 2.4.0 while you hit it on 1.10.4, three major versions apart, points the same way.

It's noisy but harmless, and there is nothing this SDK can do about it. @nbransby this one is probably worth closing as out of scope, the same way Firebase handled the flutterfire reports.

That said, I don't want to wave away the crash you actually hit. If your app really is going down, could you post the real crash trace — the `FATAL EXCEPTION` block from logcat with its `Caused by` chain? That's a different stack from the one above, and it's the one that will show what genuinely went wrong.
