### ISSUE TITLE
[Jvm Target]: Exception in thread "AWT-EventQueue-0" kotlin.NotImplementedError: An operation is not implemented. at com.google.firebase.auth.FirebaseUser.getDisplayName(FirebaseUser.kt:12)

### ISSUE THREAD

**Issue by sunildhiman90** [GitLiveApp/firebase-kotlin-sdk#688]
Hi, while using signInWithEmailAndPassword in FirebaseAuth for desktop, we are getting this exception while we are collecting authStateChanged flow and try to access displayName.

```
Exception in thread "AWT-EventQueue-0" kotlin.NotImplementedError: An operation is not implemented.
	at com.google.firebase.auth.FirebaseUser.getDisplayName(FirebaseUser.kt:12)
```

Can we instead return null values so that it will not throw exception in this case. Also Its throwing same error at email field as well. But if user is logging in with email, then correct email should be returned i guess.

**Comment by OlehSalamakha** [comment]
Got the same problem, after success login on desktop I'm not able to get mail from the current user. 
Did you find solution for it?

**Comment by JasminPambhar** [comment]
When calling FirebaseAuth.createUserWithEmailAndPassword(email, password) in a Compose Multiplatform Desktop (JVM) project using firebase-kotlin-sdk, the following runtime exception occurs:

kotlin.NotImplementedError: An operation is not implemented.
    at com.google.firebase.auth.FirebaseAuth.createUserWithEmailAndPassword(FirebaseAuth.kt:428)
